/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
static yyconst short int yy_accept[382] =
    {   0,
        0,    0,  107,  105,  104,  104,   92,  105,   98,   91,
      105,   86,   87,   96,   95,   83,   94,   90,   97,   49,
       48,   84,   80,   99,   85,  100,  103,   46,   46,   88,
       89,  101,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   81,  102,
       82,   93,  104,   79,    0,   57,    0,   65,   82,   74,
       66,    0,    0,   63,   71,   61,   72,   62,   73,    0,
       52,   64,   53,   49,    0,    0,   49,   49,    0,   49,
       48,   48,   48,   48,   89,   81,   88,   70,   76,   78,
       77,   69,   46,    0,    0,   67,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,    8,   46,   46,   46,   46,   46,   46,   16,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   68,   75,   57,    0,    0,    0,    0,   50,    0,
        0,   58,    0,   52,    0,   53,    0,   51,   49,   49,
       49,   49,    0,   47,   48,   48,   48,   48,   60,   59,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   14,   46,   46,   18,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,    0,    0,    0,    0,    0,   52,    0,   53,   51,
       49,    0,    0,   47,    0,   47,   47,   48,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,    1,   46,
        3,    4,   46,   46,   46,   46,   10,   11,   46,   46,
       15,   46,   19,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   32,   46,   46,    0,    0,
        0,    0,    0,    0,   47,   47,    0,   54,   47,   47,
       46,   46,   38,   46,   46,   46,   46,   46,   46,   46,
        2,    5,   46,   46,   46,   46,   13,   46,   46,   46,
       46,   23,   46,   46,   46,   46,   46,   46,   30,   46,

       46,   34,    0,   55,    0,   56,   54,   47,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,    9,
       12,   17,   46,   46,   22,   24,   25,   26,   27,   28,
       46,   46,   46,   55,   56,   46,   46,   37,   46,   46,
       46,   46,   46,   46,   46,   46,    7,   46,   46,   29,
       46,   46,   35,   36,   39,   40,   46,   46,   46,   46,
       45,    6,   20,   21,   31,   33,   46,   42,   46,   46,
       41,   46,   46,   46,   46,   46,   46,   46,   44,   43,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   34,   34,   36,   34,   37,   34,   38,
       34,   34,   39,   40,   41,   34,   34,   42,   34,   34,
       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   34,   57,   58,   59,   60,
       61,   62,   34,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    7,    7,
        1,    1,    1,    1,    1,    3,    7,    7,    7,    7,
        7,    7,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    3,    1,    1,    8,    6,    6,    7,
        7,    7,    6,    8,    8,    8,    8,    8,    8,    9,
        8,    8,    9,    8,    9,    8,    9,    8,    9,    8,
        8,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[391] =
    {   0,
        0,    0,  688,  689,   74,   76,  663,   75,   57,   76,
      642,  689,  689,  661,   72,  689,   73,   71,  660,  105,
       90,  658,  689,   93,  658,   68,  689,    0,   96,  689,
      689,  657,  125,  614,  616,   79,   33,   70,   45,  617,
       42,  616,  624,  111,  605,  110,  613,  618,  689,   88,
      689,  689,  130,  689,  106,  175,  120,  689,  689,  689,
      689,  105,  126,  689,  689,  689,  689,  689,  689,  657,
      165,  689,  173,  215,  230,  240,  132,  123,  656,  128,
      257,  171,  152,  161,  689,  689,  689,  646,  689,  689,
      689,  645,    0,  170,  624,  689,  141,  606,  605,  613,

      605,  602,  597,  606,  607,  594,  606,  593,  608,  595,
      601,  587,  588,  585,  585,  588,  585,  582,    0,  150,
      586,  174,  584,  149,  173,  588,  581,  637,  199,  166,
      585,  689,  689,  263,  635,  224,  266,    0,  689,  261,
        0,  689,  277,  689,  294,  689,  283,  299,  221,  689,
      603,  580,    0,  292,  279,  689,  601,  578,  689,  689,
      579,  573,  572,  573,  571,  582,  566,  580,  564,  560,
      564,  576,  571,  559,  221,  573,  571,  567,  559,  565,
      568,    0,  554,  558,    0,  559,  556,  546,  544,  546,
      548,  555,  541,  539,  539,  541,  531,  534,  535,  537,

      525,  319,  359,  324,  405,  329,  363,  342,  409,  689,
      689,  202,  289,  303,  353,  234,  334,  689,  517,  510,
      502,  495,  504,  501,  502,  487,  499,  490,    0,  492,
        0,    0,  483,  491,  480,  487,    0,    0,  481,  478,
        0,  482,    0,  477,  477,  476,  473,  485,  474,  477,
      481,  480,  477,  467,  471,    0,  459,  471,  350,    0,
      143,    0,  451,  460,  352,  689,  464,  468,  486,  453,
      450,  453,    0,  449,  443,  449,  438,  446,  453,  449,
        0,    0,  438,  439,  424,  415,    0,  421,  401,  408,
      401,    0,  409,  406,  402,  386,  395,  396,    0,  387,

      390,    0,  472,  476,  496,  500,  689,  689,  152,  394,
      391,  386,  380,  373,  388,  380,  383,  354,  354,    0,
        0,    0,  365,  365,    0,    0,    0,    0,    0,    0,
      361,  354,  347,  689,  689,  340,  349,    0,  332,  348,
      349,  333,  338,  337,  327,  314,    0,  293,  288,    0,
      292,  288,    0,    0,    0,    0,  275,  274,  278,  267,
        0,    0,    0,    0,    0,    0,  252,    0,  257,  229,
        0,  216,  203,  192,  194,   92,   87,   70,    0,    0,
      689,  558,  567,  571,  578,  585,  590,  592,  594,  596
    } ;

static yyconst short int yy_def[391] =
    {   0,
      381,    1,  381,  381,  381,  381,  381,  382,  381,  381,
      383,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  384,  384,  381,
      381,  381,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  381,  381,
      381,  381,  381,  381,  382,  381,  385,  381,  381,  381,
      381,  383,  386,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  387,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  384,  382,  383,  381,  384,  384,  384,  384,

      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  381,  381,  381,  381,  381,  382,  388,  381,  383,
      389,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  390,  387,  381,  381,  381,  381,  381,  381,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  382,  382,  383,  383,  381,  381,  381,  381,  381,
      381,  390,  390,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  382,  203,
      383,  205,  381,  381,  381,  381,  381,  381,  381,  381,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,

      384,  384,  381,  381,  381,  381,  381,  381,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  381,  381,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  384,  384,
        0,  381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static yyconst short int yy_nxt[765] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       29,   28,   30,    4,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   28,   41,   28,   42,   28,   28,
       28,   28,   43,   44,   45,   46,   47,   48,   28,   28,
       28,   49,   50,   51,   52,   53,   53,   53,   53,   56,
       58,   59,   60,   65,  111,   70,   67,   71,   71,   71,
       71,   91,   92,  112,  119,   66,   68,   69,   86,   61,

       94,  120,  116,   95,   73,  117,   81,   81,   81,   81,
       56,  132,  139,   87,   94,   88,   89,   95,   57,   73,
       76,   74,   74,   75,   75,   82,  108,  113,  128,  114,
       83,   53,   53,  109,  380,   76,  137,  137,  115,  110,
       77,   76,  140,  140,  379,   78,   79,   84,   63,   57,
      139,   97,   98,   99,  378,   83,   76,  100,  151,  101,
      133,  102,   80,  103,  104,  123,  124,  149,  150,  129,
       78,  105,  150,   79,   56,  125,  134,  134,  126,   94,
      152,   71,   71,   71,   71,  149,   63,  157,  138,   71,
       71,   71,   71,  150,  141,  143,  144,  150,  161,  336,

      144,  156,  191,  145,  146,  162,  155,  184,  146,  158,
      135,  156,  337,   57,  185,  135,  143,  144,  155,  192,
      193,  199,  144,  200,  145,  146,  156,  187,   94,   73,
      146,   74,   74,   75,   75,  194,  156,  188,  189,  263,
      136,  377,  135,  376,   73,   76,   75,   75,   75,   75,
       77,  147,  375,  147,  197,   78,  148,  148,  148,  148,
       76,  150,  198,  263,  134,  134,   76,   94,  139,  269,
       56,   73,   80,   81,   81,   81,   81,  204,  204,  374,
       78,   76,  202,  202,  233,  234,  150,   76,  206,  373,
      206,  270,   82,  207,  207,  207,  207,   83,  135,  148,

      148,  148,  148,  135,   63,  208,  213,  208,   76,   57,
      209,  209,  209,  209,   84,  148,  148,  148,  148,  156,
      372,  371,   83,   56,  370,  369,  264,  214,  136,  215,
      210,  139,  216,  368,  210,  259,  259,  367,  265,  366,
      261,  261,  365,  266,  156,  207,  207,  207,  207,  217,
      264,  210,  364,  215,   56,  363,  210,  216,  209,  209,
      209,  209,   57,   56,  267,  362,  267,   63,  266,  268,
      268,  268,  268,  361,  266,  260,  260,  260,  260,  207,
      207,  207,  207,  360,  359,  260,  260,  260,  260,  260,
      260,  265,  266,   57,  144,  358,  357,  356,  144,  266,

      355,  354,   57,  353,  352,  351,  260,  260,  260,  260,
      260,  260,  139,  350,  349,  144,  348,  266,  347,  346,
      144,  262,  262,  262,  262,  209,  209,  209,  209,  345,
      344,  262,  262,  262,  262,  262,  262,  343,  342,  341,
      146,  340,  339,  338,  146,  333,  332,  331,   63,  330,
      329,  328,  262,  262,  262,  262,  262,  262,  327,  326,
      325,  146,  303,  324,  303,  323,  146,  304,  304,  304,
      304,  305,  322,  305,  321,  320,  306,  306,  306,  306,
      268,  268,  268,  268,  268,  268,  268,  268,  304,  304,
      304,  304,  304,  304,  304,  304,  319,  318,  317,  307,

      316,  315,  314,  307,  313,  312,  311,  334,  310,  309,
      308,  334,  306,  306,  306,  306,  306,  306,  306,  306,
      307,  308,  302,  301,  300,  307,  299,  298,  334,  297,
      296,  335,  295,  334,  294,  335,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  278,  335,  277,  276,  275,  274,  335,   55,  273,
       55,   55,   55,   55,   55,   55,   55,   62,  272,   62,
      271,   62,   62,   62,   62,   62,   93,   93,   93,   93,
       55,   55,  258,   55,  257,  256,   55,   62,   62,  255,
       62,  254,  253,   62,  154,  154,  154,  203,  203,  205,

      205,  212,  212,  252,  251,  250,  249,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  218,  211,  211,   94,
      201,   94,  196,  195,  190,  186,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,   63,  160,  159,
      153,  142,  131,  130,  127,  122,  121,  118,  107,  106,
       96,   90,   85,   72,   64,   63,   54,  381,    3,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381
    } ;

static yyconst short int yy_chk[765] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,    8,
        9,    9,   10,   15,   37,   18,   17,   18,   18,   18,
       18,   26,   26,   37,   41,   15,   17,   17,   24,   10,

       29,   41,   39,   29,   21,   39,   21,   21,   21,   21,
       55,   50,   62,   24,   46,   24,   24,   46,    8,   20,
       21,   20,   20,   20,   20,   21,   36,   38,   46,   38,
       21,   53,   53,   36,  378,   20,   57,   57,   38,   36,
       20,   21,   63,   63,  377,   20,   20,   21,   62,   55,
      261,   33,   33,   33,  376,   21,   20,   33,   78,   33,
       50,   33,   20,   33,   33,   44,   44,   77,   80,   46,
       20,   33,   77,   20,   94,   44,   56,   56,   44,   56,
       78,   71,   71,   71,   71,   80,  261,   83,   57,   73,
       73,   73,   73,   80,   63,   71,   71,   77,   97,  309,

       71,   84,  124,   73,   73,   97,   82,  120,   73,   83,
       56,   82,  309,   94,  120,   56,   71,   71,   84,  124,
      125,  130,   71,  130,   73,   73,   84,  122,  136,   74,
       73,   74,   74,   74,   74,  125,   82,  122,  122,  212,
       56,  375,  136,  374,   75,   74,   75,   75,   75,   75,
       74,   76,  373,   76,  129,   74,   76,   76,   76,   76,
       75,  149,  129,  212,  134,  134,   74,  134,  140,  216,
      137,   81,   74,   81,   81,   81,   81,  140,  140,  372,
       74,   75,  137,  137,  175,  175,  149,   81,  143,  370,
      143,  216,   81,  143,  143,  143,  143,   81,  134,  147,

      147,  147,  147,  134,  140,  145,  154,  145,   81,  137,
      145,  145,  145,  145,   81,  148,  148,  148,  148,  155,
      369,  367,   81,  202,  360,  359,  213,  154,  134,  154,
      148,  204,  154,  358,  148,  202,  202,  357,  214,  352,
      204,  204,  351,  214,  155,  206,  206,  206,  206,  154,
      213,  148,  349,  154,  259,  348,  148,  154,  208,  208,
      208,  208,  202,  203,  215,  346,  215,  204,  214,  215,
      215,  215,  215,  345,  217,  203,  203,  203,  203,  207,
      207,  207,  207,  344,  343,  203,  203,  203,  203,  203,
      203,  217,  265,  259,  207,  342,  341,  340,  207,  217,

      339,  337,  203,  336,  333,  332,  203,  203,  203,  203,
      203,  203,  205,  331,  324,  207,  323,  265,  319,  318,
      207,  205,  205,  205,  205,  209,  209,  209,  209,  317,
      316,  205,  205,  205,  205,  205,  205,  315,  314,  313,
      209,  312,  311,  310,  209,  301,  300,  298,  205,  297,
      296,  295,  205,  205,  205,  205,  205,  205,  294,  293,
      291,  209,  263,  290,  263,  289,  209,  263,  263,  263,
      263,  264,  288,  264,  286,  285,  264,  264,  264,  264,
      267,  267,  267,  267,  268,  268,  268,  268,  303,  303,
      303,  303,  304,  304,  304,  304,  284,  283,  280,  268,

      279,  278,  277,  268,  276,  275,  274,  304,  272,  271,
      270,  304,  305,  305,  305,  305,  306,  306,  306,  306,
      268,  269,  258,  257,  255,  268,  254,  253,  304,  252,
      251,  306,  250,  304,  249,  306,  248,  247,  246,  245,
      244,  242,  240,  239,  236,  235,  234,  233,  230,  228,
      227,  226,  306,  225,  224,  223,  222,  306,  382,  221,
      382,  382,  382,  382,  382,  382,  382,  383,  220,  383,
      219,  383,  383,  383,  383,  383,  384,  384,  384,  384,
      385,  385,  201,  385,  200,  199,  385,  386,  386,  198,
      386,  197,  196,  386,  387,  387,  387,  388,  388,  389,

      389,  390,  390,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  184,  183,  181,  180,  179,  178,  177,
      176,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  158,  157,  152,  151,  135,
      131,  128,  127,  126,  123,  121,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   98,   95,   92,   88,
       79,   70,   48,   47,   45,   43,   42,   40,   35,   34,
       32,   25,   22,   19,   14,   11,    7,    3,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler.l"
#define INITIAL 0
#line 26 "compiler.l"
#include "y.tab.h"
#include <stdlib.h>
#include <string.h>

int column = 0;
void count();
#line 669 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 35 "compiler.l"


#line 823 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 689 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "compiler.l"
{ return(AUTO); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "compiler.l"
{ return(BREAK); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "compiler.l"
{ return(CASE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "compiler.l"
{ return(CHAR); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "compiler.l"
{ return(CONST); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "compiler.l"
{ return(CONTINUE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "compiler.l"
{ return(DEFAULT); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "compiler.l"
{ return(DO); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "compiler.l"
{ return(DOUBLE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 46 "compiler.l"
{ return(ELSE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 47 "compiler.l"
{ return(ENUM); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 48 "compiler.l"
{ return(EXTERN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 49 "compiler.l"
{ return(FLOAT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "compiler.l"
{ return(FOR); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 51 "compiler.l"
{ return(GOTO); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 52 "compiler.l"
{ return(IF); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 53 "compiler.l"
{ return(INLINE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 54 "compiler.l"
{ return(INT); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "compiler.l"
{ return(LONG); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 56 "compiler.l"
{ return(REGISTER); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "compiler.l"
{ return(RESTRICT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "compiler.l"
{ return(RETURN); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "compiler.l"
{ return(SHORT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "compiler.l"
{ return(SIGNED); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 61 "compiler.l"
{ return(SIZEOF); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 62 "compiler.l"
{ return(STATIC); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 63 "compiler.l"
{ return(STRUCT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 64 "compiler.l"
{ return(SWITCH); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 65 "compiler.l"
{ return(TYPEDEF); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 66 "compiler.l"
{ return(UNION); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 67 "compiler.l"
{ return(UNSIGNED); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 68 "compiler.l"
{ return(VOID); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 69 "compiler.l"
{ return(VOLATILE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 70 "compiler.l"
{ return(WHILE); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 71 "compiler.l"
{ return ALIGNAS; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 72 "compiler.l"
{ return ALIGNOF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "compiler.l"
{ return ATOMIC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "compiler.l"
{ return BOOL; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "compiler.l"
{ return COMPLEX; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "compiler.l"
{ return GENERIC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "compiler.l"
{ return IMAGINARY; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "compiler.l"
{ return NORETURN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "compiler.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "compiler.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "compiler.l"
{ return FUNC_NAME; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "compiler.l"
{ return IDENTIFIER; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 85 "compiler.l"
{ return I_CONSTANT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 86 "compiler.l"
{ return I_CONSTANT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 87 "compiler.l"
{ return I_CONSTANT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 88 "compiler.l"
{ return I_CONSTANT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 90 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 91 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 92 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 93 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 94 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 95 "compiler.l"
{ return F_CONSTANT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "compiler.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "compiler.l"
{ return ELLIPSIS; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "compiler.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "compiler.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "compiler.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "compiler.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "compiler.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "compiler.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "compiler.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "compiler.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "compiler.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "compiler.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "compiler.l"
{ return RIGHT_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "compiler.l"
{ return LEFT_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "compiler.l"
{ return INC_OP; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "compiler.l"
{ return DEC_OP; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "compiler.l"
{ return PTR_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "compiler.l"
{ return AND_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "compiler.l"
{ return OR_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "compiler.l"
{ return LE_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "compiler.l"
{ return GE_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "compiler.l"
{ return EQ_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 120 "compiler.l"
{ return NE_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 121 "compiler.l"
{ return ';'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 122 "compiler.l"
{ return '{'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 123 "compiler.l"
{ return '}'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 124 "compiler.l"
{ return ','; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 125 "compiler.l"
{ return ':'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 126 "compiler.l"
{ return '='; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 127 "compiler.l"
{ return '('; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 128 "compiler.l"
{ return ')'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 129 "compiler.l"
{ return '['; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 130 "compiler.l"
{ return ']'; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 131 "compiler.l"
{ return '.'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 132 "compiler.l"
{ return '&'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 133 "compiler.l"
{ return '!'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 134 "compiler.l"
{ return '~'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 135 "compiler.l"
{ return '-'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 136 "compiler.l"
{ return '+'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 137 "compiler.l"
{ return '*'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 138 "compiler.l"
{ return '/'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 139 "compiler.l"
{ return '%'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "compiler.l"
{ return '<'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 141 "compiler.l"
{ return '>'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 142 "compiler.l"
{ return '^'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 143 "compiler.l"
{ return '|'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 144 "compiler.l"
{ return '?'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 146 "compiler.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 147 "compiler.l"
{ /* discard bad characters */ }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 149 "compiler.l"
ECHO;
	YY_BREAK
#line 1436 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 381);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 149 "compiler.l"



void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	//printf("-->%d ",column);
	//ECHO;
}